export const facts = [
 {id:'services', keys:['service','offer','hire','help','edit','video editor','work together','specialt','specializ','unsa imo'], question:'What does she specialize in? Can she turn my footage into a finished video? What creative services does Jade offer?', answer:'Jade works on story-led and long-form video editing, Reels, music videos, promotional and advocacy videos, direction, cinematography, graphic design, and photography.',link:'#about',label:'Explore services'},
 {id:'watch',keys:['watch','start watching','best work','recommend','sample','portfolio','projects','showreel'],question:'Which projects should I watch first? Show me her best editing and filmmaking samples.',answer:'Start with KAPA for narrative filmmaking, The Wedding Dance for trailer storytelling, or Panalangin and my tears ricochet for music-led editing. For a shorter commercial format, try the Program Promotional Reel in Recent edits.',link:'#video',label:'View selected work'},
 {id:'book',keys:['book','contact','email','inquire','enquiry','inquiry','reach','message','get in touch','collaborat','start a project'],question:'How do I contact Jade or book a project? What should I send in my project brief?',answer:'Send Jade your idea, the type of video or design you need, your timeline, and any references. Use the contact form below or email jadephillineofficial@gmail.com. Jade will confirm the scope and next steps herself.',link:'#contact',label:'Start a conversation'},
 {id:'price',keys:['price','cost','rate','budget','charge','payment','discount','quote','pila','bayad'],question:'How much does editing cost? What are her rates, packages and payment terms?',answer:'Jade’s portfolio does not list fixed rates or packages. Tell her about the footage, final length, deliverables, and deadline so she can give you a quote. I can’t confirm prices or payment terms on her behalf.',link:'#contact',label:'Ask Jade for a quote'},
 {id:'availability',keys:['available','availability','deadline','turnaround','urgent','schedule','when','revision'],question:'Is Jade available now? How fast is her turnaround and how many revisions are included?',answer:'Jade is open to remote project inquiries. Availability, turnaround, and revisions depend on the brief and need to be confirmed directly with her.',link:'#contact',label:'Check your timeline with Jade'},
 {id:'location',keys:['location','where','based','remote','philippines','bayugan','asa','timezone'],question:'Where is Jade based? Can she work remotely with international clients?',answer:'Jade is based in Bayugan City, Philippines, and is open to remote projects. Share your location and working preferences when you get in touch.',link:'#contact',label:'Contact Jade'},
 {id:'tools',keys:['software','tool','capcut','canva','davinci','resolve','premiere','program','color grade'],question:'Which editing and design software does Jade use? Does she know DaVinci Resolve?',answer:'CapCut Desktop is Jade’s primary editing tool. She uses Canva for graphic and publication design, and has basic DaVinci Resolve skills that she is continuing to develop.',link:'#about',label:'See the creative toolkit'},
 {id:'experience',keys:['experience','since','background','education','qualification','who is','about jade','communication'],question:'Who is Jade? What is her experience and educational background?',answer:'Jade Philline Monforte is a video editor and visual storyteller. She began private freelance projects in 2023. Her Communication training at Father Saturnino Urios University informs her work across film, social content, and visual design.',link:'#about',label:'Meet Jade'},
 {id:'kapa',keys:['kapa','cape','land reform','agrarian','farmer'],question:'What is KAPA Cape about and what did Jade do on the film?',answer:'KAPA (Cape) follows a girl whose childhood dream of being a hero grows into a struggle with poverty, injustice, and displacement, until land reform brings a chance to claim the home her mother fought for. Jade’s credits are Writer, Director, Cinematographer, and Videographer.',link:'./watch.html?film=kapa',label:'Watch KAPA'},
 {id:'wedding',keys:['wedding dance','the wedding','childless','awiyao','lumnay'],question:'What is The Wedding Dance about? What are Jade’s credits?',answer:'The Wedding Dance explores a couple’s love under the pressure to have a child. Jade is credited as Editor, Director, Writer, Cinematographer, and Videographer on the trailer.',link:'./watch.html?film=wedding',label:'Watch The Wedding Dance'},
 {id:'homework',keys:['homework','study','studying','sadness','hidden emotions'],question:'What is Homework about? Did Jade make it?',answer:'Homework is an emotional short film about a young woman’s unspoken sadness during a night of studying. Her eyes, the song, color grading, and atmosphere carry the feelings beneath the ordinary routine. Jade is the Editor, Director, Writer, Cinematographer, and Videographer.',link:'./watch.html?film=homework',label:'Watch Homework'},
 {id:'panalangin',keys:['panalangin','prayer','puppy love','1990','college crush','first love'],question:'What is Panalangin Prayer about? Is it a romance music video?',answer:'Panalangin (Prayer) is a music video about college puppy love in the late 1990s. Jade developed the concept and script, directed, shot, and edited it.',link:'./watch.html?film=panalangin',label:'Watch Panalangin'},
 {id:'tears',keys:['tears','ricochet','infidelity','cheat','betrayal'],question:'What is my tears ricochet about? What was Jade’s role?',answer:'my tears ricochet tells a story of infidelity and betrayal, with the images and edit shaped around the song’s emotional rhythm. Jade developed the concept and script, directed, shot, and edited it.',link:'./watch.html?film=tears',label:'Watch my tears ricochet'},
 {id:'anna',keys:['anna','alone','character','portrait','stacey','dylan','belle','theatre','theater','photography'],question:'What is Anna Alone? Does Jade do photography and art direction?',answer:'Anna Alone is a featured theatre visual project: a central poster and portraits of Stacey, Dylan, Belle, and Anna. Jade’s contributions cover Photography, Art Direction, Photo Editing, and Poster Design.',link:'#featured-project',label:'Explore Anna Alone'},
 {id:'design',keys:['design','poster','graphic','pubmat','publication','campaign','branding'],question:'Can Jade make graphic designs, posters, and social media publication materials?',answer:'Yes. The Graphic Design section includes editorial publication materials, enrollment campaigns, research recognition graphics, and film key art. Anna Alone brings her poster design and character photography together in one project.',link:'#design',label:'View design work'},
 {id:'reels',keys:['reel','short form','short-form','vertical','tiktok','instagram','social','commercial','promotional'],question:'Does Jade edit Reels and short vertical social content for brands?',answer:'Jade works on Reels and promotional content as well as films. You can watch the Program Promotional Reel, Michael Jordan DNA editing sample, Teacher Education Program video, and Coffee Painting presentation in Recent edits.',link:'./watch.html?film=reel',label:'Watch the promotional reel'},
 {id:'credits',keys:['credits','role','director','cinematograph','videograph','script','writer'],question:'Did Jade direct, write, film, and edit her projects? What were her exact contributions?',answer:'For Homework, The Wedding Dance, Panalangin, and my tears ricochet, Jade’s credits include Editor, Director, Writer, Cinematographer, and Videographer. KAPA lists Writer, Director, Cinematographer, and Videographer.',link:'#video',label:'Read the project credits'}
];
export function quickMatch(question){
 const q=question.toLowerCase().replace(/[’']/g,'');
 // Specific project names take precedence over broad terms such as “edit”.
 const projects=['kapa','wedding','homework','panalangin','tears','anna'];
 for(const id of projects){const f=facts.find(f=>f.id===id);if(f.keys.some(k=>q.includes(k)))return f;}
 const priority=['price','availability','location','tools','book','reels','design','experience','watch','credits','services'];
 for(const id of priority){const f=facts.find(f=>f.id===id);if(f.keys.some(k=>q.includes(k)))return f;}
 return null;
}
